services:
  database:
    image: 'postgres:alpine'
    env_file:
      - .env.local
    networks:
      - chord-sheets-network
    healthcheck:
      # pg_isready checks if the database is ready to accept connections
      test: [ "CMD-SHELL", "pg_isready -U main" ]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - .env.local
    networks:
      - chord-sheets-network
    depends_on:
      database:
        condition: service_healthy

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - api
      - web
    networks:
      - chord-sheets-network

  web:
    build:
      context: ./web/
      args:
        WEB_SERVER_URL: http://localhost:8000
    networks:
      - chord-sheets-network

networks:
  chord-sheets-network:
    driver: bridge
